export default [
    {
        label:'数据采集',
        children:[
            {label:'数据采集',path:'/index/dataAcquisition'},
            {label:'数据列表',path:'/index/dataList'}
        ]
    },
    {
        label:'数据展示',
        children:[
            {label:'WaterAll数据',path:'/index/waterAllData'},
            {label:'WaterMonth数据',path:'/index/waterMonth'},
            {label:'WTarget数据',path:'/index/waterTarget'},
            {label:'地表水标准',path:''}
        ]
    },
    {
        label:'水质评估分析',
        children:[
            {label:'基本统计分析',path:''},
            {label:'地表水单指标等级评价',path:'/index/surfaceWater'},
            {label:'水质指标周期性分析',path:''},
            {label:'水质指标相关性分析',path:''},
            {label:'管网水水质分析',path:''},
            {label:'N1指数',path:''},
            {label:'口感指数',path:'/index/tasteIndex'},
            {label:'污水可生化性分析',path:''}
        ]
    },
    {
        label:'综合水质评价',
        children:[
            {label:'单因子评价法',path:''},
            {label:'主成分分析法',path:''},
            {label:'模糊模式识别法',path:''},
            {label:'BP神经网络评价法',path:''},
            {label:'健康风险综合指',path:'/index/healthRisk'}
        ]
    },
    {
        label:'实时数据分析',
        children:[
            {label:'实时数据展示',path:'/index/realDisplay'},
            {label:'实时数据预警预判',path:''}
        ]
    }
]
